* Tareas a realizar:
** Práctica04
*** Aldo Daniel Licona Gómez
i. Calcula la paridad par de las siguientes cadenas:
  a) 1010111
  b) 1000010
  c) 1001101 1111000
  d) 1111111 0000001
ii. Calcula la paridad impar de las siguientes cadenas:
  a) 0101011
  b) 0000011
  c) 0010111 0011111
  d) 1111110 0111111
  
*** Adrián Aguilera Moreno
Cada equipo tendrá que realizar las siguientes ac9vidades explicando y con capturas de pantalla
de lo siguiente:
 i. Crear un archivo (del 9po, tamaño y extensión que prefieran).

 ii. Investigar cuál es el procedimiento (comando, aplicación, etc..) a realizar para obtener el
 checksum de su archivo mediante consola/terminal.

 iii. Obtener el checksum de su archivo con al menos 2 algoritmos diferentes.
 NOTA: No se pueden ocupar herramientas online (si9os de internet).

 iv. Enviar el archivo a través de internet a otro integrante del equipo, obtener el checksum
 del archivo recibido y compararlo con el original.
 NOTA: Realizar este procedimiento en un entorno Windows y Linux.

 v. Investigue y explique al menos 3 ejemplos de la implementación de esta comprobación.

 vi. Realice un programa en Python donde se ejemplifique la implementación del checksum.
 El programa debe de ser capaz de simular una comunicación Emisor-Receptor, es decir, de
 calcular el checksum de una cadena de datos y luego verificar si se ha producido un error
 durante la transmisión calculando nuevamente el checksum y comparándolo con el valor
 recibido. (25 ptos).

*** Francisco Contreras Ibarra

i. Calcula el CRC con los siguientes datos y realiza la comprobación:
  a) Trama: x^8 + x^7 + x^6 + x^5 + x^2 + 1 , G(x) = x^4 + x^2 + 1
  b) Trama: 110101111, G(x) = x^4 + x + 1
  Nota: Para la entrega de los ejercicios deben colocar todo el procedimiento, se
  pueden realizar a mano y escanear o tomarle foto y anexarla en el reporte. 
ii. Realiza un programa en Python donde se calcule el CRC (Valor 15pts).
  a. La trama se debe mostrar en binario y G(x) debera mostrar tanto en polinomio
  como en binario.
  b. Se debe mostrar el valor de r e indicar cuantos 0 se deben agregar.
  c. Antes de realizar la division mostrar el valor de x^r * M(x)
  d. Calcular el valor de CRC.
  e. Mostrar el valor que tiene T.
  Nota: Para la evidencia en el reporte usen la información de los ejercicios
  anteriores(Trama y G(x) )
  NOTA: las evidencias con respecto a los códigos de programación a entregar serán las siguientes:
  - En su reporte anexarán una captura de pantalla de su código completo con los elementos
  necesarios para evitar el plagio.
  - Capturas de pantalla de la ejecución del código mediante terminal, así como el resultado.
  - No es necesario que el programa cuente con una interfaz gráfica, si la quieren agregar es
opcional.
  - En la plataforma deberán de anexar el código fuente o si su programa 9ene interfaz gráfica, el
ejecutable.
  - Si al momento de calificar el código se sospecha de plagio, el equipo será acreedor de una
sanción. Dependiendo de la gravedad del asunto será desde penalización en la calificación como
la anulación de la misma.
